version: "3"

services:
  front:
    build: ./front
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./front:/usr/front
      - front-deps:/usr/front/node_modules
  api:
    build:
      context: ./api
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./api:/go/src/github.com/topheman/my-docker-fullstack-project/api
    ports:
      - "5000:5000"

volumes:
  front-deps: