version: "3.4"

services:
  # no ports exposed by default, (api is proxied through docker networks)
  # in development, it's exposed on port 5000, see docker-composed.override.yml
  api:
    image: topheman/my-docker-fullstack-project_api_production
    build:
      target: production
      context: ./api