version: "3.4"

services:
  api:
    image: topheman/my-docker-fullstack-project_api_development
    command: sh -c "echo \"development\" && go get github.com/pilu/fresh && fresh"
    build:
      target: builder
    volumes:
      - ./api:/go/src/github.com/topheman/my-docker-fullstack-project/api
  front:
    image: topheman/my-docker-fullstack-project_front_development
    build:
      context: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front:/usr/front
      - front-deps:/usr/front/node_modules

volumes:
  front-deps: