version: 2
jobs:
  build:
    machine:
      # We need the latest version of docker-engine because we use docker-compose file format v3.4
      # For the compatibility between docker-engine version and docker-compose file format, see https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix
      # For the list of available circleci images, see https://circleci.com/docs/2.0/configuration-reference/#machine
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: "Infos"
          command: |
            docker-compose --version
            docker version
      - run:
          name: "Build development images"
          command: docker-compose build
      - run:
          name: "Test front"
          command: docker-compose run --rm -e CI=true front npm run -s test
      - run:
          name: "Test api"
          command: docker-compose run --rm api go test -run ''